baseURL = 'http://example.org/'
languageCode = 'en-us'
title = '我的博客'

theme = "m10c"

[params]
  author = "Alex Pu"
  description = "Alex，坐标上海，从事后端开发 5 年，拥有红帽 RHCSA、RHCE 认证，常用技术栈为 PHP、Go、Python、JavaScript、Node.js。热衷研究新技术，享受书写代码的感觉，相信编程是一门艺术，编程丰富生活。"
  avatar = ""
  favicon = "https://pudongping.github.io/medias/favicon.png"