
baseURL = "https://101.126.67.179:1313/"
languageCode = 'zh-cn'
title = '小飞龙的Blog'

theme = "m10c"

paginate = 8

[params]
  author = "小飞龙"
  description = "小飞龙\n退役ACMer\n目前在南京\ngo后端开发社畜"
  avatar = "https://s21.ax1x.com/2024/09/12/pAnG0O0.jpg"
  favicon = "https://s21.ax1x.com/2024/09/12/pAnG0O0.jpg"