
baseURL = "https://101.126.67.179:1313/hugo/"
languageCode = 'zh-cn'
title = '小飞龙的Blog'

theme = "m10c"

paginate = 8

[params]
  author = "小飞龙"
  description = "小飞龙 退役ACMer 目前在南京当go后端开发社畜"
  avatar = "https://free2.yunpng.top/2024/09/05/66d94ec0e149e.jpg"
  favicon = "https://free2.yunpng.top/2024/09/05/66d94ec0e149e.jpg"